# If .bash_profile exists, bash doesn't read .profile by default. Make sure it does
if [[ -f ~/.profile ]]; then
  . ~/.profile
fi

# If .bashrc exists, get the aliases and functions
if [[ -f ~/.bashrc ]]; then
  . ~/.bashrc
fi

if [ -f ~/.git-completion.bash ]; then
    . ~/.git-completion.bash
fi

#  File generated by update-locale
LANG="en_EN.UTF-8"
LC_NUMERIC="en_EN.UTF-8"
LC_TIME="en_EN.UTF-8"
LC_MONETARY="en_EN.UTF-8"
LC_PAPER="en_EN.UTF-8"
LC_NAME="en_EN.UTF-8"
LC_ADDRESS="en_EN.UTF-8"
LC_TELEPHONE="en_EN.UTF-8"
LC_MEASUREMENT="en_EN.UTF-8"
LC_IDENTIFICATION="en_EN.UTF-8"
LC_CTYPE="en_EN.UTF-8"
LC_ALL="en_EN.UTF-8"
